language: python
python: "3.6"
    
 # don't clone more than necessary
git:
  depth: 1
    
 # Install dependencies
install:
  - pip install -r requirements.txt

env:
    - TRAVIS_SECURE_ENV_VARS = true

script: 
  - coverage run manage.py test Game/tests.py